plugins:
  wiki_contributors_enabled:
    default: true
    client: true
  wiki_contributors_limit:
    default: 10
    min: 1
    max: 50
    client: true
  wiki_contributors_show_edit_count:
    default: true
    client: true
